"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Job = {id:string;title:string;status:string;taken_by:string|null;created_at:string};
type Response = {id:string;job_id:string;provider_id:string;message:string|null;quoted_price:number|null;status:string;created_at:string;provider?:{full_name:string;area:string|null;profile_photo_url:string|null}|null};

export default function ManageJobsPage(){
 const router=useRouter(); const [jobs,setJobs]=useState<Job[]>([]); const [responses,setResponses]=useState<Record<string,Response[]>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState("");
 async function load(){setError(""); const {data:a}=await supabase.auth.getUser(); if(!a.user){router.push("/login");return;} const {data:j,error:je}=await supabase.from("jobs").select("id,title,status,taken_by,created_at").eq("customer_id",a.user.id).order("created_at",{ascending:false}); if(je){setError(je.message);setLoading(false);return;} setJobs(j||[]); const ids=(j||[]).map(x=>x.id); if(ids.length){const {data:r,error:re}=await supabase.from("job_responses").select("id,job_id,provider_id,message,quoted_price,status,created_at,provider:profiles!job_responses_provider_id_fkey(full_name,area,profile_photo_url)").in("job_id",ids).order("created_at",{ascending:true}); if(re)setError(re.message); else {const grouped:Record<string,Response[]>={}; (r||[]).forEach((x:any)=>{(grouped[x.job_id] ||= []).push(x)});setResponses(grouped)}} setLoading(false)}
 useEffect(()=>{load()},[]);
 async function hire(job:Job,response:Response){if(!confirm(`Hire ${response.provider?.full_name || "this worker"} for ${job.title}?`))return;setBusy(response.id);setError("");const {error:e}=await supabase.from("jobs").update({taken_by:response.provider_id,status:"taken"}).eq("id",job.id);if(e){setError(e.message);setBusy("");return;}await supabase.from("job_responses").update({status:"accepted"}).eq("id",response.id);await supabase.from("job_responses").update({status:"rejected"}).eq("job_id",job.id).neq("id",response.id).eq("status","pending");setBusy("");await load()}
 if(loading)return <main style={{padding:32,fontFamily:"system-ui"}}>Loading your jobs…</main>;
 return <main className="page"><section className="wrap"><button className="back" onClick={()=>router.push("/")}>← Marketplace</button><div className="brand">🇰🇪 Kazi za <span>Kenya</span></div><h1>Manage my jobs</h1><p className="intro">Review workers who responded to jobs you posted and choose who you hired.</p>{error&&<div className="error">{error}</div>}{jobs.length===0?<div className="empty">You have not posted a job yet.</div>:jobs.map(job=><article className="job" key={job.id}><div className="jobhead"><div><h2>{job.title}</h2><span>{job.status.replaceAll("_"," ")}</span></div><b>{(responses[job.id]||[]).length} response{(responses[job.id]||[]).length===1?"":"s"}</b></div>{(responses[job.id]||[]).length===0?<p className="none">No worker responses yet.</p>:<div className="applicants">{(responses[job.id]||[]).map(r=><div className="applicant" key={r.id}><div className="person"><div className="avatar">{r.provider?.full_name?.[0]||"W"}</div><div><strong>{r.provider?.full_name||"Worker"}</strong><small>{r.provider?.area||"Kenya"}</small></div></div>{r.message&&<p>{r.message}</p>}{r.quoted_price!=null&&<div className="price">Quoted: KSh {Number(r.quoted_price).toLocaleString()}</div>}<div className="actions"><span className={`state ${r.status}`}>{r.status}</span>{job.status==="available"&&r.status==="pending"&&<button disabled={busy===r.id} onClick={()=>hire(job,r)}>{busy===r.id?"Hiring…":"🤝 I hired this worker"}</button>}</div></div>)}</div>}</article>)}</section><style jsx>{styles}</style></main>}
const styles=`*{box-sizing:border-box}.page{min-height:100vh;background:#f3f6f3;padding:30px 16px;font-family:Inter,system-ui,sans-serif;color:#17221b}.wrap{max-width:820px;margin:auto}.back{border:0;background:transparent;color:#15803d;font-weight:750;cursor:pointer;padding:0}.brand{font-size:20px;font-weight:850;margin:10px 0 25px}.brand span{color:#15803d}h1{font-size:32px;margin:0 0 5px}.intro{color:#66736b;margin:0 0 24px}.job{background:#fff;border:1px solid #dce4dc;border-radius:17px;padding:20px;margin:14px 0;box-shadow:0 7px 24px rgba(27,43,31,.06)}.jobhead{display:flex;justify-content:space-between;gap:14px;align-items:start}.jobhead h2{font-size:19px;margin:0 0 5px}.jobhead span{font-size:11px;text-transform:uppercase;color:#637168}.jobhead>b{font-size:12px;color:#15803d}.applicants{display:grid;gap:10px;margin-top:15px}.applicant{border:1px solid #e0e7e1;border-radius:12px;padding:14px}.person{display:flex;gap:10px;align-items:center}.avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#e7f7ec;color:#15803d;font-weight:900}.person strong,.person small{display:block}.person small{color:#748078;margin-top:2px}.applicant p{font-size:13px;line-height:1.5;color:#526057}.price{font-size:13px;font-weight:800;margin-top:8px}.actions{display:flex;justify-content:space-between;align-items:center;margin-top:12px;gap:10px}.actions button{border:0;border-radius:9px;background:#16803d;color:#fff;padding:10px 13px;font-weight:800;cursor:pointer}.actions button:disabled{opacity:.55}.state{font-size:10px;text-transform:uppercase;font-weight:850;padding:5px 8px;border-radius:999px;background:#edf2ed}.state.accepted{background:#e4f6e9;color:#147335}.state.rejected{background:#f5eded;color:#8b4141}.none,.empty{color:#758179}.empty{background:#fff;border:1px solid #dce4dc;border-radius:15px;padding:25px}.error{background:#fff1f1;border:1px solid #efcaca;color:#9b2929;border-radius:10px;padding:11px 13px;margin:12px 0}@media(max-width:600px){.jobhead{display:block}.jobhead>b{display:block;margin-top:8px}.actions{align-items:flex-start;flex-direction:column}.actions button{width:100%}}`;