"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Geo={latitude:number;longitude:number;accuracy:number};
type LocationSource="device"|"area";
type Point={latitude:number;longitude:number};
type ExistingJob={id:string;latitude:number|null;longitude:number|null};
const allowedTypes=new Set(["image/jpeg","image/png","image/webp"]);
const DIFFERENT_AREA_KM=30;
function safeExt(f:File){return f.type==="image/png"?"png":f.type==="image/webp"?"webp":"jpg"}
function parseBudget(v:string){const n=v.match(/[\d,]+(?:\.\d+)?/g)?.map(x=>Number(x.replace(/,/g,""))).filter(Number.isFinite)??[];if(!n.length)return{min:null,max:null};if(n.length===1)return{min:n[0],max:n[0]};return{min:Math.min(n[0],n[1]),max:Math.max(n[0],n[1])}}
function distanceKm(a:Point,b:Point){const r=6371,toRad=(v:number)=>v*Math.PI/180,dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude),lat1=toRad(a.latitude),lat2=toRad(b.latitude);const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(h)))}
function clusterCount(points:Point[]){const clusters:Point[]=[];for(const p of points){if(!clusters.some(c=>distanceKm(c,p)<=DIFFERENT_AREA_KM))clusters.push(p)}return clusters.length}

export default function PostJobPage(){
 const router=useRouter(); const [photos,setPhotos]=useState<File[]>([]); const [submitted,setSubmitted]=useState(false); const [checkingAuth,setCheckingAuth]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [geo,setGeo]=useState<Geo|null>(null); const [locating,setLocating]=useState(false); const [locationError,setLocationError]=useState(""); const [savedLocationSource,setSavedLocationSource]=useState<LocationSource|null>(null);
 const [title,setTitle]=useState(""); const [service,setService]=useState(""); const [description,setDescription]=useState(""); const [area,setArea]=useState(""); const [budgetText,setBudgetText]=useState("");
 useEffect(()=>{let active=true;supabase.auth.getUser().then(({data})=>{if(!active)return;if(!data.user){router.replace("/login?next=%2Fpost-job");return}setCheckingAuth(false)});return()=>{active=false}},[router]);
 function locate(){setLocationError("");if(!navigator.geolocation){setLocationError("This device does not support location sharing.");return}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{setGeo({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy});setLocating(false)},e=>{setLocationError(e.code===1?"Location permission was not granted. We will use your typed area approximately.":"We could not get your current location. We will use your typed area approximately.");setLocating(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
 function choosePhotos(files:File[]){const selected=files.slice(0,5);const bad=selected.find(f=>!allowedTypes.has(f.type)||f.size>5*1024*1024);if(bad){setPhotos([]);setError("Photos must be JPG, PNG or WebP and no larger than 5 MB each.");return}setError("");setPhotos(selected)}
 async function geocodeArea(cleanArea:string){try{const response=await fetch("/api/geocode-area",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({area:cleanArea,region:"Nairobi",countryCode:"KE"})});if(!response.ok)return null;const result=await response.json();const latitude=Number(result.latitude),longitude=Number(result.longitude);if(!Number.isFinite(latitude)||!Number.isFinite(longitude))return null;return{latitude,longitude}}catch{return null}}
 async function resolveLocation(areaPoint:Point|null){if(geo)return{latitude:geo.latitude,longitude:geo.longitude,accuracy:geo.accuracy,source:"device" as const};if(areaPoint)return{...areaPoint,accuracy:5000,source:"area" as const};return null}
 async function enforceLocationSpamGuard(userId:string,newAreaPoint:Point|null){const{data:jobs,error:jobsError}=await supabase.from("jobs").select("id,latitude,longitude").eq("customer_id",userId).eq("status","available");if(jobsError)throw jobsError;const existing=((jobs??[]) as ExistingJob[]).map(j=>({latitude:Number(j.latitude),longitude:Number(j.longitude)})).filter((p:Point)=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude));if(existing.length<3||clusterCount(existing)<3||!newAreaPoint)return;const isNewDistantArea=!existing.some((p:Point)=>distanceKm(p,newAreaPoint)<=DIFFERENT_AREA_KM);if(!isNewDistantArea)return;if(!geo)throw new Error("Location protection: you already have open jobs in 3 different areas. To post another job in a new area, please tap ‘Use my current location’ so workers know this location is genuine.");if(distanceKm(geo,newAreaPoint)>DIFFERENT_AREA_KM)throw new Error("Location protection: this new job area is far from your current device location. Please confirm the correct job location before posting. This protects workers from misleading location spam.")}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setSaving(true);try{const{data:authData,error:authError}=await supabase.auth.getUser();if(authError||!authData.user){router.replace("/login?next=%2Fpost-job");return}const cleanTitle=title.trim(),category=service.trim(),cleanDescription=description.trim(),cleanArea=area.trim();if(!cleanTitle||!category||!cleanDescription||!cleanArea||!budgetText.trim())throw new Error("Please complete all required job details.");const budget=parseBudget(budgetText.trim());const areaPoint=await geocodeArea(cleanArea);await enforceLocationSpamGuard(authData.user.id,areaPoint);const resolved=await resolveLocation(areaPoint);const{data:job,error:insertError}=await supabase.from("jobs").insert({customer_id:authData.user.id,title:cleanTitle,description:cleanDescription,category,budget_min:budget.min,budget_max:budget.max,county:"Nairobi",area:cleanArea,location_text:`${cleanArea}, Nairobi, Kenya`,latitude:resolved?.latitude??null,longitude:resolved?.longitude??null,country_code:"KE",location_source:resolved?.source??"legacy",location_accuracy_m:resolved?.accuracy??null,status:"available"}).select("id").single();if(insertError||!job)throw insertError||new Error("The job could not be created.");const uploadedPaths:string[]=[];try{for(let i=0;i<photos.length;i++){const file=photos[i],path=`jobs/${authData.user.id}/${job.id}/${crypto.randomUUID()}.${safeExt(file)}`;const{error:uploadError}=await supabase.storage.from("kazi-media").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;uploadedPaths.push(path);const{data:urlData}=supabase.storage.from("kazi-media").getPublicUrl(path);const{error:photoError}=await supabase.from("job_photos").insert({job_id:job.id,uploaded_by:authData.user.id,storage_path:path,photo_url:urlData.publicUrl});if(photoError)throw photoError}}catch(photoErr){for(const path of uploadedPaths)await supabase.storage.from("kazi-media").remove([path]);await supabase.from("jobs").delete().eq("id",job.id);throw new Error(photoErr instanceof Error?`Photo upload failed: ${photoErr.message}`:"Photo upload failed. Please try again.")}setSavedLocationSource(resolved?.source??null);setSubmitted(true)}catch(err){setError(err instanceof Error?err.message:"We could not post your job. Please try again.")}finally{setSaving(false)}}
 if(checkingAuth)return <main className="page"><section className="card success"><h1>Checking your account…</h1><p>You need to be signed in so this job belongs to the correct employer.</p><style jsx>{styles}</style></section></main>;
 if(submitted)return <main className="page"><section className="card success"><div className="mark">✓</div><h1>Your request is posted</h1><p>Your job is live in Kazi za Kenya{savedLocationSource==="device"?" with its precise private position saved for nearby matching":savedLocationSource==="area"?" with an approximate area position saved for map matching":""}. Workers can now discover it.</p><button onClick={()=>router.push("/")}>Back to Kazi za Kenya</button></section><style jsx>{styles}</style></main>;
 return <main className="page"><section className="card"><button className="back" type="button" onClick={()=>router.push("/")}>← Back</button><div className="brand">🇰🇪 Kazi za <span>Kenya</span></div><h1>What do you need done?</h1><p className="intro">Tell nearby workers what you need. Share the device position of the job for accurate nearby matching, or type the area and we will place it approximately on the map.</p><form onSubmit={submit}>
 <label>Job title<input required name="title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Fix a leaking kitchen sink"/></label><label>Service or category<input required name="service" value={service} onChange={e=>setService(e.target.value)} placeholder="e.g. Plumbing, cleaning, moving"/></label><label>Description<textarea required name="description" value={description} onChange={e=>setDescription(e.target.value)} rows={5} placeholder="Describe the work that needs to be done"/></label>
 <div className="locationBox"><b>📍 Job position</b><p>Use the device at the job location for the most accurate map position. If you do not share GPS, the typed area will be converted to an approximate map position. To protect workers from location spam, a fourth open job in another distant area may require current-location confirmation.</p><button className="locate" type="button" disabled={locating} onClick={locate}>{locating?"Finding location…":geo?"✓ Location captured — update it":"Use my current location"}</button>{geo&&<small className="ok">Position captured · accuracy about {Math.round(geo.accuracy)} m. Exact coordinates are not printed publicly.</small>}{locationError&&<small className="locError">{locationError}</small>}</div>
 <div className="two"><label>Area<input required name="area" value={area} onChange={e=>setArea(e.target.value)} placeholder="e.g. Kilimani"/></label><label>Approximate budget<input required name="budget" value={budgetText} onChange={e=>setBudgetText(e.target.value)} placeholder="e.g. KSh 2,000 - 4,000"/></label></div>
 <label>Photos <small>(optional, up to 5 · JPG/PNG/WebP · 5 MB each)</small><input className="file" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>choosePhotos(Array.from(e.target.files||[]))}/></label>{photos.length>0&&<div className="photoNote">📷 {photos.length} photo{photos.length===1?"":"s"} ready to upload</div>}{error&&<div className="error">{error}</div>}<div className="notice">GPS is optional for normal posting. If an account already has open jobs across 3 distant areas, Kazi za Kenya may require location confirmation before allowing another distant job.</div><button className="submit" type="submit" disabled={saving}>{saving?"Posting & locating…":"Post what I need"}</button></form></section><style jsx>{styles}</style></main>
}
const styles=`*{box-sizing:border-box}.page{min-height:100vh;background:#f3f6f3;padding:30px 16px;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:#17221b}.card{max-width:680px;margin:auto;background:#fff;border:1px solid #dce4dc;border-radius:20px;padding:28px;box-shadow:0 12px 40px rgba(27,43,31,.1)}.brand{font-size:20px;font-weight:850;margin:8px 0 26px}.brand span{color:#15803d}h1{font-size:30px;margin:0 0 8px}.intro{color:#66736b;line-height:1.55;margin:0 0 24px}.back{border:0;background:transparent;color:#15803d;font-weight:750;padding:0;cursor:pointer}form{display:grid;gap:17px}label{display:grid;gap:7px;font-size:13px;font-weight:800}small{font-weight:500;color:#78847c}input,textarea{width:100%;border:1px solid #d5ddd6;border-radius:11px;padding:12px 13px;outline:0;background:#fff;font:inherit;font-weight:500}input:focus,textarea:focus{border-color:#16803d;box-shadow:0 0 0 3px rgba(22,128,61,.09)}textarea{resize:vertical}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.locationBox{border:1px solid #cfe1d3;background:#f5fbf6;border-radius:13px;padding:14px}.locationBox p{font-size:12px;color:#607066;line-height:1.5;margin:5px 0 10px}.locate{border:1px solid #99c7a6;background:#fff;color:#156f37;border-radius:10px;padding:10px 12px;font-weight:800;cursor:pointer}.locate:disabled{opacity:.6}.ok,.locError{display:block;margin-top:9px}.ok{color:#257342}.locError{color:#9f2020}.file{padding:10px}.photoNote{font-size:12px;color:#52705b}.notice{background:#eef8f1;border:1px solid #cfe8d6;border-radius:11px;padding:12px 14px;color:#386347;font-size:12px;line-height:1.5}.error{background:#fff1f1;border:1px solid #f2c4c4;color:#9f1d1d;border-radius:11px;padding:11px 13px;font-size:13px}.submit,.success button{border:0;border-radius:11px;background:#16803d;color:#fff;padding:13px 18px;font-weight:800;cursor:pointer}.submit:disabled{opacity:.65}.success{text-align:center;margin-top:10vh}.mark{width:58px;height:58px;border-radius:50%;background:#e7f7ec;color:#16803d;display:grid;place-items:center;margin:0 auto 18px;font-size:30px;font-weight:900}.success p{color:#66736b;line-height:1.6;max-width:500px;margin:0 auto 22px}@media(max-width:600px){.card{padding:21px}.two{grid-template-columns:1fr}h1{font-size:25px}}`;