"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "../lib/supabase";

type Row = { id:string; name?:string; full_name?:string; trade?:string; title?:string; category?:string; area?:string|null; latitude?:number|null; longitude?:number|null; budget_min?:number|null; budget_max?:number|null };

export default function MapClient(){
 const [mode,setMode]=useState<"workers"|"jobs">("workers"); const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Row|null>(null);
 useEffect(()=>{let alive=true; (async()=>{setLoading(true); if(!supabase){setRows([]);setLoading(false);return;} if(mode==="workers"){const {data}=await supabase.from("profiles").select("id,full_name,area,latitude,longitude,bio").eq("role","provider").eq("is_active",true).not("latitude","is",null).limit(100); if(alive)setRows((data||[]).map((x:any)=>({...x,name:x.full_name,trade:"Independent worker"})));} else {const {data}=await supabase.from("jobs").select("id,title,category,area,latitude,longitude,budget_min,budget_max").eq("status","open").not("latitude","is",null).limit(100); if(alive)setRows(data||[]);} setLoading(false)})(); return()=>{alive=false}},[mode]);
 const positioned=useMemo(()=>rows.map((r,i)=>{const lat=r.latitude??-1.286; const lng=r.longitude??36.817; const x=Math.max(7,Math.min(93,50+(lng-36.817)*85)); const y=Math.max(10,Math.min(90,50-(lat+1.286)*85)); return {...r,x,y,i}}),[rows]);
 return <main className="page"><style>{css}</style><header><Link href="/new-home" className="brand">Kazi <i>za</i> <b>Kenya</b></Link><div className="switch"><button className={mode==="workers"?"on":""} onClick={()=>{setMode("workers");setSelected(null)}}>Find a Worker</button><button className={mode==="jobs"?"on job":""} onClick={()=>{setMode("jobs");setSelected(null)}}>Find Jobs</button></div></header><section className="intro"><div><span>🇰🇪 Nairobi first</span><h1>{mode==="workers"?"Workers near you":"Jobs near you"}</h1><p>{loading?"Loading nearby results…":`${rows.length} results found from Kazi za Kenya.`}</p></div><Link href={mode==="workers"?"/new-home/offer-service":"/new-home/need-service"} className="action">{mode==="workers"?"Offer a service":"Post a job"}</Link></section><section className="wrap"><div className="map"><div className="roads r1"/><div className="roads r2"/><div className="roads r3"/><div className="label">NAIROBI</div>{positioned.map(r=><button key={r.id} className={`pin ${mode}`} style={{left:`${r.x}%`,top:`${r.y}%`}} onClick={()=>setSelected(r)}>{mode==="workers"?"●":"◆"}</button>)}<div className="you">You</div></div><aside><h2>{mode==="workers"?"Nearby workers":"Nearby jobs"}</h2>{positioned.map(r=><button className={`item ${selected?.id===r.id?"selected":""}`} key={r.id} onClick={()=>setSelected(r)}><b>{mode==="workers"?r.name:r.title}</b><small>{mode==="workers"?r.trade:r.category} · {r.area||"Nairobi"}</small></button>)}{!loading&&!rows.length&&<p className="empty">No public results with a location yet. Be the first to add one.</p>}{selected&&<div className="detail"><h3>{mode==="workers"?selected.name:selected.title}</h3><p>{mode==="workers"?selected.trade:selected.category}</p><p>📍 {selected.area||"Nairobi"}</p><Link href={mode==="workers"?`/new-home/profile/${selected.id}`:`/new-home/job/${selected.id}`}>Open {mode==="workers"?"profile":"job"} →</Link></div>}</aside></section></main>
}
const css=`*{box-sizing:border-box}.page{min-height:100vh;background:#f5f7f3;color:#111;font-family:Arial,sans-serif}.page header{height:76px;background:#fff;border-bottom:1px solid #ddd;display:flex;align-items:center;justify-content:space-between;padding:0 5vw}.brand{font-size:26px;font-weight:900;text-decoration:none;color:#111}.brand i{font-style:normal;color:#bb0000}.brand b{color:#006b3c}.switch{display:flex;background:#eee;padding:4px;border-radius:12px}.switch button{border:0;background:transparent;padding:10px 15px;border-radius:9px;font-weight:800}.switch .on{background:#111;color:#fff}.switch .on.job{background:#bb0000}.intro{max-width:1200px;margin:auto;padding:28px 5vw 18px;display:flex;justify-content:space-between;align-items:end;gap:20px}.intro span{color:#006b3c;font-weight:800}.intro h1{font-size:34px;margin:8px 0}.intro p{color:#666;margin:0}.action{background:#006b3c;color:#fff;padding:12px 18px;border-radius:10px;text-decoration:none;font-weight:800}.wrap{margin:0 5vw 40px;background:#fff;border:1px solid #ddd;border-radius:20px;overflow:hidden;display:grid;grid-template-columns:1fr 340px;min-height:620px}.map{position:relative;min-height:620px;background:#dcebdc;background-image:linear-gradient(#b7cfb7 1px,transparent 1px),linear-gradient(90deg,#b7cfb7 1px,transparent 1px);background-size:35px 35px}.roads{position:absolute;height:12px;background:#fff;box-shadow:0 0 0 1px #cbd8c7;border-radius:20px}.r1{width:90%;left:5%;top:48%;transform:rotate(12deg)}.r2{width:70%;left:15%;top:30%;transform:rotate(-25deg)}.r3{width:65%;left:20%;top:70%;transform:rotate(-8deg)}.label{position:absolute;top:20px;left:20px;background:#ffffffdd;padding:8px 12px;border-radius:8px;font-weight:900;letter-spacing:2px}.pin{position:absolute;transform:translate(-50%,-50%);width:38px;height:38px;border-radius:50%;border:4px solid #fff;box-shadow:0 5px 15px #0005;color:#fff;cursor:pointer;z-index:2}.pin.workers{background:#006b3c}.pin.jobs{background:#bb0000}.you{position:absolute;left:50%;top:55%;background:#111;color:#fff;padding:7px 10px;border-radius:20px;font-size:11px;font-weight:800}aside{padding:20px;overflow:auto}aside h2{margin-top:0}.item{display:block;width:100%;text-align:left;background:#fff;border:1px solid #ddd;border-radius:12px;padding:14px;margin:9px 0;cursor:pointer}.item.selected{border:2px solid #111}.item small{display:block;color:#666;margin-top:5px}.detail{margin-top:15px;padding:16px;border-radius:14px;background:#f1f4ef}.detail h3{margin:0 0 6px}.detail p{color:#666;margin:6px 0}.detail a{display:inline-block;margin-top:8px;color:#006b3c;font-weight:900;text-decoration:none}.empty{color:#666;line-height:1.6}@media(max-width:800px){.intro{display:block}.action{display:inline-block;margin-top:15px}.wrap{grid-template-columns:1fr}.map{min-height:430px}.switch button{padding:9px 8px;font-size:12px}}
`;
