"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Job={id:string;title:string;status:string;customer_id:string;taken_by:string|null;completion_requested_by:string|null;created_at:string;customer?:{full_name:string}|null};
export default function MyWork(){const router=useRouter();const [uid,setUid]=useState("");const [jobs,setJobs]=useState<Job[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState("");
async function load(){const {data:a}=await supabase.auth.getUser();if(!a.user){router.push("/login?next=%2Fmy-work");return;}setUid(a.user.id);const {data,error:e}=await supabase.from("jobs").select("id,title,status,customer_id,taken_by,completion_requested_by,created_at,customer:profiles!jobs_customer_id_fkey(full_name)").eq("taken_by",a.user.id).order("created_at",{ascending:false});if(e)setError(e.message);else setJobs((data||[]) as any);setLoading(false)}
useEffect(()=>{load()},[]);
async function change(job:Job,status:string){setBusy(job.id);setError("");const patch:any={status};if(status==="completion_pending")patch.completion_requested_by=uid;const {error:e}=await supabase.from("jobs").update(patch).eq("id",job.id);if(e)setError(e.message);setBusy("");await load()}
async function confirmCompletion(job:Job){setBusy(job.id);const {error:e}=await supabase.from("jobs").update({status:"completed",completion_confirmed_by:uid}).eq("id",job.id);if(e)setError(e.message);setBusy("");await load()}
async function message(job:Job){setBusy(job.id);let {data:c,error:e}=await supabase.from("conversations").select("id").eq("job_id",job.id).eq("employer_id",job.customer_id).eq("provider_id",uid).maybeSingle();if(e){setError(e.message);setBusy("");return;}if(!c){const r=await supabase.from("conversations").insert({job_id:job.id,employer_id:job.customer_id,provider_id:uid}).select("id").single();if(r.error){setError(r.error.message);setBusy("");return;}c=r.data;}setBusy("");router.push(`/messages/${c.id}`)}
if(loading)return <main style={{padding:32,fontFamily:"system-ui"}}>Loading your work…</main>;return <main className="page"><section className="wrap"><button className="back" onClick={()=>router.push("/")}>← Marketplace</button><div className="brand">🇰🇪 Kazi za <span>Kenya</span></div><h1>My work</h1><p className="intro">Jobs where an employer hired you.</p>{error&&<div className="error">{error}</div>}{!jobs.length?<div className="empty">You do not have a hired job yet.</div>:jobs.map(j=><article className="card" key={j.id}><div><h2>{j.title}</h2><p>Employer: {j.customer?.full_name||"Customer"}</p><b>{j.status.replaceAll("_"," ")}</b></div><div className="actions"><button onClick={()=>message(j)} disabled={busy===j.id}>💬 Message employer</button>{j.status==="taken"&&<button onClick={()=>change(j,"in_progress")} disabled={busy===j.id}>🔨 Work has started</button>}{j.status==="in_progress"&&<button onClick={()=>change(j,"completion_pending")} disabled={busy===j.id}>✅ Request completion</button>}{j.status==="completion_pending"&&j.completion_requested_by!==uid&&<button onClick={()=>confirmCompletion(j)} disabled={busy===j.id}>✅ Confirm completion</button>}{["completed","archived"].includes(j.status)&&<button onClick={()=>router.push(`/rate-job?job=${j.id}`)}>⭐ Rate employer</button>}</div></article>)}</section><style jsx>{`*{box-sizing:border-box}.page{min-height:100vh;background:#f3f6f3;padding:30px 16px;font-family:Inter,system-ui;color:#17221b}.wrap{max-width:800px;margin:auto}.back{border:0;background:transparent;color:#15803d;font-weight:800;cursor:pointer}.brand{font-size:20px;font-weight:900;margin:12px 0 24px}.brand span{color:#15803d}h1{font-size:32px;margin:0}.intro{color:#68766d}.card,.empty{background:white;border:1px solid #dce5dd;border-radius:16px;padding:20px;margin:15px 0}.card{display:flex;justify-content:space-between;gap:20px}.card h2{margin:0 0 6px}.card p{color:#69766e}.card b{font-size:11px;text-transform:uppercase;color:#15803d}.actions{display:flex;flex-direction:column;gap:8px;min-width:190px}.actions button{border:0;border-radius:9px;background:#16803d;color:white;padding:10px;font-weight:800;cursor:pointer}.actions button:first-child{background:#17221b}.error{background:#fff0f0;color:#9a2828;padding:12px;border-radius:10px}@media(max-width:650px){.card{display:block}.actions{margin-top:16px}}`}</style></main>}
