"use client";

import { FormEvent,useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { supabase } from "../../../lib/supabase";

type Msg={id:string;sender_id:string;body:string;created_at:string};
type Conv={id:string;job_id:string;employer_id:string;provider_id:string;job?:{title:string}|null};
export default function Messages(){const p=useParams<{id:string}>();const router=useRouter();const [uid,setUid]=useState("");const [conv,setConv]=useState<Conv|null>(null);const [msgs,setMsgs]=useState<Msg[]>([]);const [body,setBody]=useState("");const [error,setError]=useState("");const [sending,setSending]=useState(false);
async function load(){const {data:a}=await supabase.auth.getUser();if(!a.user){router.push("/login");return;}setUid(a.user.id);const {data:c,error:ce}=await supabase.from("conversations").select("id,job_id,employer_id,provider_id,job:jobs!conversations_job_id_fkey(title)").eq("id",p.id).single();if(ce){setError("Conversation not found or you do not have access.");return;}setConv(c as any);const {data:m,error:me}=await supabase.from("messages").select("id,sender_id,body,created_at").eq("conversation_id",p.id).order("created_at",{ascending:true});if(me)setError(me.message);else setMsgs(m||[])}
useEffect(()=>{load();const ch=supabase.channel(`messages-${p.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${p.id}`},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[p.id]);
async function send(e:FormEvent){e.preventDefault();const text=body.trim();if(!text)return;setSending(true);setError("");const {error:se}=await supabase.from("messages").insert({conversation_id:p.id,sender_id:uid,body:text});if(se)setError(se.message);else{setBody("");await load()}setSending(false)}
return <main className="page"><section className="wrap"><button className="back" onClick={()=>router.back()}>← Back</button><div className="brand">🇰🇪 Kazi za <span>Kenya</span></div><h1>{conv?.job?.title||"Job messages"}</h1><p className="note">Messages are visible only to the employer and hired worker for this job.</p>{error&&<div className="error">{error}</div>}<div className="chat">{!msgs.length?<div className="empty">No messages yet. Start the conversation about the job.</div>:msgs.map(m=><div key={m.id} className={m.sender_id===uid?"bubble mine":"bubble"}><div>{m.body}</div><small>{new Date(m.created_at).toLocaleString()}</small></div>)}</div>{conv&&<form onSubmit={send}><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} placeholder="Write a message about this job…"/><button disabled={sending||!body.trim()}>{sending?"Sending…":"Send message"}</button></form>}</section><style jsx>{`*{box-sizing:border-box}.page{min-height:100vh;background:#f3f6f3;padding:25px 14px;font-family:Inter,system-ui;color:#17221b}.wrap{max-width:760px;margin:auto}.back{border:0;background:transparent;color:#15803d;font-weight:800;cursor:pointer}.brand{font-weight:900;font-size:19px;margin:12px 0 22px}.brand span{color:#15803d}h1{margin:0;font-size:27px}.note{color:#6a766e;font-size:13px}.chat{background:white;border:1px solid #dce5dd;border-radius:16px;min-height:360px;padding:18px;margin:18px 0;display:flex;flex-direction:column;gap:10px}.bubble{max-width:76%;background:#eef2ee;padding:10px 12px;border-radius:12px 12px 12px 3px}.bubble.mine{align-self:flex-end;background:#def3e4;border-radius:12px 12px 3px 12px}.bubble small{display:block;color:#78847c;font-size:9px;margin-top:5px}.empty{margin:auto;color:#78847c}form{display:flex;gap:9px}textarea{flex:1;min-height:64px;resize:vertical;border:1px solid #cdd8cf;border-radius:12px;padding:12px;font:inherit}form button{border:0;border-radius:11px;background:#16803d;color:white;padding:0 22px;font-weight:850;cursor:pointer}form button:disabled{opacity:.5}.error{background:#fff0f0;color:#9a2828;padding:11px;border-radius:9px}@media(max-width:550px){form{display:block}form button{width:100%;padding:13px;margin-top:7px}.bubble{max-width:88%}}`}</style></main>}
