"use client";
import {createPortal} from "react-dom";
import {useEffect,useMemo,useState} from "react";
import {usePathname} from "next/navigation";
import {supabase} from "../lib/supabase";

type Profile={id:string;full_name:string;profile_kind:"worker"|"employer";country_code:string;country_name:string;area:string|null;avatar_url:string|null;bio:string|null;years_experience:number|null;occupation:string|null;latitude:number|null;longitude:number|null};
type Job={id:string;employer_profile_id:string;title:string;description:string;budget_min:number|null;budget_max:number|null;currency_code:string|null;country_code:string;country_name:string;area:string|null;latitude:number|null;longitude:number|null;sort_order:number};
type Media={id:number;owner_type:"profile"|"job";owner_id:string;image_url:string;caption:string|null;sort_order:number};
const NORTH=new Set(["DK","EE","FI","IS","IE","LV","LT","NO","SE","GB","AT","CZ","DE","HU","LI","PL","SK","SI","CH","BE","FR","LU","MC","NL","AL","AD","BA","HR","GR","IT","MT","ME","MK","PT","SM","RS","ES","BY","BG","MD","RO","RU","UA"]),KEY="anydaywork-marketplace-country";
const code=(v:unknown)=>String(v||"").trim().toUpperCase();
const mode=()=>{const t=Array.from(document.querySelectorAll<HTMLElement>(".main-tab")).find(x=>x.classList.contains("active"));return(t?.textContent||"").toLowerCase().includes("job")?"jobs":"workers"};
function mapObj(){const el=document.querySelector<HTMLElement>(".leaflet-container") as any;if(!el)return{el:null,map:null};const w=window as any;return{el,map:w.__kzkMarketplaceMap||el.__kzkMarketplaceMap||el._leaflet_map||Object.values(w).find((v:any)=>v&&typeof v==="object"&&v._container===el&&typeof v.flyTo==="function")}}
function fly(x:{latitude:number|null;longitude:number|null}){const{map}=mapObj();if(map&&x.latitude!=null&&x.longitude!=null)try{map.flyTo([Number(x.latitude),Number(x.longitude)],14,{animate:true,duration:1})}catch{}}
function money(v:number|null,c:string|null){if(v==null)return"";try{return new Intl.NumberFormat(undefined,{style:"currency",currency:(c||"EUR"),maximumFractionDigits:0}).format(v)}catch{return`${c||"EUR"} ${v}`}}
async function allMedia(){const out:Media[]=[];for(let from=0;;from+=500){const{data,error}=await supabase.from("demo_media").select("id,owner_type,owner_id,image_url,caption,sort_order").eq("dev_only",true).order("id").range(from,from+499);if(error)return{data:out,error};const page=(data||[]) as Media[];out.push(...page);if(page.length<500)return{data:out,error:null}}}
export default function MarketplaceNorthernDemoContent(){const pathname=usePathname();const[country,setCountry]=useState("");const[profiles,setProfiles]=useState<Profile[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[media,setMedia]=useState<Media[]>([]);const[workerMount,setWorkerMount]=useState<HTMLElement|null>(null);const[jobMount,setJobMount]=useState<HTMLElement|null>(null);const[selectedWorker,setSelectedWorker]=useState<Profile|null>(null);const[selectedJob,setSelectedJob]=useState<Job|null>(null);
useEffect(()=>{if(pathname!=="/")return;try{setCountry(code(localStorage.getItem(KEY)))}catch{}const h=(e:Event)=>setCountry(code((e as CustomEvent<{countryCode?:string}>).detail?.countryCode));window.addEventListener("anydaywork:country-changed",h as EventListener);return()=>window.removeEventListener("anydaywork:country-changed",h as EventListener)},[pathname]);
useEffect(()=>{if(pathname!=="/")return;let alive=true;async function load(){const[p,j,m]=await Promise.all([supabase.from("demo_profiles").select("id,full_name,profile_kind,country_code,country_name,area,avatar_url,bio,years_experience,occupation,latitude,longitude").eq("dev_only",true).in("country_code",Array.from(NORTH)),supabase.from("demo_jobs").select("id,employer_profile_id,title,description,budget_min,budget_max,currency_code,country_code,country_name,area,latitude,longitude,sort_order").eq("dev_only",true).in("country_code",Array.from(NORTH)),allMedia()]);if(!alive)return;if(!p.error)setProfiles((p.data||[]) as Profile[]);if(!j.error)setJobs((j.data||[]) as Job[]);if(!m.error)setMedia((m.data||[]) as Media[])}void load();const t=setInterval(load,30000);return()=>{alive=false;clearInterval(t)}},[pathname]);
useEffect(()=>{if(pathname!=="/")return;const find=()=>{setWorkerMount(document.getElementById("anyday-south-workers-mount"));setJobMount(document.getElementById("anyday-south-jobs-mount"))};find();const o=new MutationObserver(find);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[pathname]);
const photos=(t:"profile"|"job",id:string)=>media.filter(x=>x.owner_type===t&&x.owner_id===id).sort((a,b)=>a.sort_order-b.sort_order);const employers=useMemo(()=>new Map(profiles.filter(x=>x.profile_kind==="employer").map(x=>[x.id,x])),[profiles]);const workers=profiles.filter(x=>x.profile_kind==="worker"&&x.country_code===country);const shownJobs=jobs.filter(x=>x.country_code===country);const active=NORTH.has(country);
useEffect(()=>{if(!active||pathname!=="/"||!profiles.length)return;let group:any=null,tries=0,t=0;const mount=()=>{const{el,map}=mapObj(),L=(window as any).L;if(!el||!map||!L)return false;try{el.__anydayNorthGroup?.remove?.()}catch{}group=L.layerGroup();if(mode()==="workers")profiles.filter(x=>x.profile_kind==="worker").forEach(x=>{if(x.latitude==null||x.longitude==null)return;const icon=L.divIcon({className:"anyday-south-map-marker",html:'<div class="anyday-south-pin anyday-south-pin-worker">E</div>',iconSize:[34,34],iconAnchor:[17,17]});const m=L.marker([x.latitude,x.longitude],{icon});m.bindTooltip(`${x.full_name} · EXAMPLE WORKER · ${x.area||x.country_name}`);m.on("click",()=>{fly(x);setSelectedWorker(x)});m.addTo(group)});else jobs.forEach(x=>{if(x.latitude==null||x.longitude==null)return;const icon=L.divIcon({className:"anyday-south-map-marker",html:'<div class="anyday-south-pin anyday-south-pin-job">J</div>',iconSize:[34,34],iconAnchor:[17,17]});const m=L.marker([x.latitude,x.longitude],{icon});m.bindTooltip(`${x.title} · EXAMPLE JOB · ${x.area||x.country_name}`);m.on("click",()=>{fly(x);setSelectedJob(x)});m.addTo(group)});group.addTo(map);el.__anydayNorthGroup=group;return true};t=window.setInterval(()=>{tries++;if(mount()||tries>40)clearInterval(t)},250);mount();return()=>{clearInterval(t);try{group?.remove?.()}catch{}}},[active,pathname,profiles,jobs,country]);
if(pathname!=="/"||!active)return null;const wp=workerMount&&mode()==="workers"?createPortal(<div className="anyday-south-list">{workers.map(p=><button key={p.id} className="anyday-south-card" onClick={()=>{fly(p);setSelectedWorker(p)}}><img src={p.avatar_url||""} alt="Illustrative example profile"/><div><b>{p.full_name}</b><span>EXAMPLE</span><p>{p.occupation}</p><small>📍 {p.area}, {p.country_name}</small><em>📷 {photos("profile",p.id).length} work photos</em></div></button>)}</div>,workerMount):null;const jp=jobMount&&mode()==="jobs"?createPortal(<div className="anyday-south-list">{shownJobs.map(j=>{const e=employers.get(j.employer_profile_id);return <button key={j.id} className="anyday-south-card anyday-south-job" onClick={()=>{fly(j);setSelectedJob(j)}}><img src={e?.avatar_url||""} alt="Illustrative example employer"/><div><b>{j.title}</b><span>EXAMPLE JOB</span><p>{e?.full_name} · {j.area}</p><small>{money(j.budget_min,j.currency_code)} - {money(j.budget_max,j.currency_code)}</small><em>📷 {photos("job",j.id).length} job photos</em></div></button>})}</div>,jobMount):null;const wph=selectedWorker?photos("profile",selectedWorker.id):[],jph=selectedJob?photos("job",selectedJob.id):[],emp=selectedJob?employers.get(selectedJob.employer_profile_id):null;
return <>{wp}{jp}{selectedWorker&&createPortal(<div className="anyday-south-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedWorker(null)}}><section className="anyday-south-modal"><button className="anyday-south-close" onClick={()=>setSelectedWorker(null)}>×</button><header><img src={selectedWorker.avatar_url||""} alt="Illustrative example profile"/><div><h2>{selectedWorker.full_name}</h2><p>{selectedWorker.occupation}</p><b>EXAMPLE — NOT A REAL USER</b></div></header><div className="anyday-south-box">📍 {selectedWorker.area}, {selectedWorker.country_name}</div><h3>About</h3><p>{selectedWorker.bio}</p><h3>Photos of my work</h3><div className="anyday-south-gallery">{wph.map(x=><figure key={x.id}><img src={x.image_url} alt={x.caption||"Illustrative work example"}/><figcaption>{x.caption}</figcaption></figure>)}</div><p className="anyday-south-note">Illustrative example imagery only. This profile cannot be contacted, hired, rated or reviewed.</p></section></div>,document.body)}{selectedJob&&createPortal(<div className="anyday-south-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedJob(null)}}><section className="anyday-south-modal"><button className="anyday-south-close" onClick={()=>setSelectedJob(null)}>×</button><header><img src={emp?.avatar_url||""} alt="Illustrative example employer"/><div><h2>{emp?.full_name}</h2><p>Employer / job poster</p><b>EXAMPLE — NOT A REAL USER</b></div></header><div className="anyday-south-box">📍 {selectedJob.area}, {selectedJob.country_name}</div><h3>{selectedJob.title}</h3><strong>{money(selectedJob.budget_min,selectedJob.currency_code)} - {money(selectedJob.budget_max,selectedJob.currency_code)}</strong><p>{selectedJob.description}</p><h3>Photos of the work needed</h3><div className="anyday-south-gallery">{jph.map(x=><figure key={x.id}><img src={x.image_url} alt={x.caption||"Illustrative job example"}/><figcaption>{x.caption}</figcaption></figure>)}</div><p className="anyday-south-note">Illustrative example job only. It cannot be applied to, accepted, messaged, rated or reviewed.</p></section></div>,document.body)}</>}
