"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { usePathname } from "next/navigation";
import { supabase } from "../lib/supabase";

type LiveJob={id:string;title:string;description:string;category:string|null;budget_min:number|null;budget_max:number|null;county:string;area:string|null;road:string|null;location_text:string|null;latitude:number|null;longitude:number|null;created_at:string};
function money(v:number|null){return v===null?null:`KSh ${Number(v).toLocaleString("en-KE")}`}
function budget(j:LiveJob){const a=money(j.budget_min),b=money(j.budget_max);return a&&b?`${a} - ${b}`:a?`From ${a}`:b?`Up to ${b}`:"Budget to discuss"}
function when(s:string){const m=Math.max(0,Math.floor((Date.now()-new Date(s).getTime())/60000));if(m<60)return m<=1?"Just now":`${m} min ago`;const h=Math.floor(m/60);if(h<24)return `${h} hr${h===1?"":"s"} ago`;const d=Math.floor(h/24);return `${d} day${d===1?"":"s"} ago`}

export default function MarketplaceLiveJobs(){
 const pathname=usePathname(); const [mount,setMount]=useState<HTMLElement|null>(null); const [jobs,setJobs]=useState<LiveJob[]>([]); const [selected,setSelected]=useState<LiveJob|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState("");
 useEffect(()=>{if(pathname!=="/")return;let stopped=false;let observer:MutationObserver|null=null;function attach(){const titles=Array.from(document.querySelectorAll<HTMLElement>(".section-title"));const title=titles.find(n=>(n.textContent||"").replace(/\s+/g," ").trim()==="Jobs people need done");if(!title||!title.parentElement)return;let node=document.getElementById("kzk-live-jobs-mount") as HTMLElement|null;if(!node){node=document.createElement("div");node.id="kzk-live-jobs-mount";title.insertAdjacentElement("afterend",node)}if(!stopped)setMount(node)}attach();observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});function capture(e:Event){const i=e.target as HTMLInputElement|null;if(!i||i.tagName!=="INPUT")return;const p=(i.placeholder||"").toLowerCase();if(p.includes("search")||p.includes("service")||p.includes("area"))setSearch(i.value||"")}document.addEventListener("input",capture,true);return()=>{stopped=true;observer?.disconnect();document.removeEventListener("input",capture,true)}},[pathname]);
 useEffect(()=>{if(pathname!=="/")return;let active=true;async function load(){setLoading(true);const {data,error}=await supabase.rpc("get_public_marketplace_jobs");if(!active)return;if(error){setError(error.message);setJobs([])}else{setError(null);setJobs((data||[]) as LiveJob[])}setLoading(false)}void load();const timer=window.setInterval(load,20000);return()=>{active=false;clearInterval(timer)}},[pathname]);
 useEffect(()=>{if(!mount)return;const parent=mount.parentElement;if(!parent)return;const cards=Array.from(parent.children).filter(el=>el!==mount&&(el as HTMLElement).classList?.contains("job-card")) as HTMLElement[];if(!loading&&!error)cards.forEach(c=>c.style.display="none");else cards.forEach(c=>c.style.removeProperty("display"));return()=>cards.forEach(c=>c.style.removeProperty("display"))},[mount,loading,error]);
 // Bridge real database coordinates into the existing Leaflet map without rewriting the stable homepage.
 useEffect(()=>{if(pathname!=="/"||loading||error)return;const w=window as any;let cancelled=false;let tries=0;const timer=window.setInterval(()=>{tries++;if(cancelled)return;const mapEl=document.querySelector<HTMLElement>(".leaflet-container");const L=w.L;if(!mapEl||!L){if(tries>30)clearInterval(timer);return}const map=(mapEl as any)._leaflet_map||Object.values(w).find((v:any)=>v&&typeof v==="object"&&v._container===mapEl&&typeof v.addLayer==="function");if(!map){if(tries>30)clearInterval(timer);return}clearInterval(timer);document.querySelectorAll(".kzk-live-map-marker").forEach(n=>n.remove());const group=L.layerGroup().addTo(map);jobs.filter(j=>Number.isFinite(Number(j.latitude))&&Number.isFinite(Number(j.longitude))).forEach(j=>{const icon=L.divIcon({className:"kzk-live-map-marker",html:'<div style="width:30px;height:30px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#16803d;border:3px solid white;box-shadow:0 2px 8px rgba(0,0,0,.25)"><div style="transform:rotate(45deg);text-align:center;line-height:24px;font-size:13px">🛠</div></div>',iconSize:[30,30],iconAnchor:[15,30]});const marker=L.marker([Number(j.latitude),Number(j.longitude)],{icon}).addTo(group);marker.bindTooltip(j.title);marker.on("click",()=>setSelected(j))});(mapEl as any).__kzkLiveGroup?.remove?.();(mapEl as any).__kzkLiveGroup=group},200);return()=>{cancelled=true;clearInterval(timer);const el=document.querySelector<HTMLElement>(".leaflet-container") as any;el?.__kzkLiveGroup?.remove?.();if(el)delete el.__kzkLiveGroup}},[pathname,jobs,loading,error]);
 const visible=useMemo(()=>{const q=search.toLowerCase().trim();return !q?jobs:jobs.filter(j=>`${j.title} ${j.description} ${j.category||""} ${j.area||""} ${j.road||""} ${j.location_text||""} ${j.county||""}`.toLowerCase().includes(q))},[jobs,search]);
 if(pathname!=="/"||!mount)return null;
 return createPortal(<><div className="kzk-live-wrap"><div className="kzk-live-label"><span/> Live marketplace jobs</div>{loading&&<div className="note">Loading current jobs…</div>}{!loading&&error&&<div className="note">Could not load live jobs. Showing the existing marketplace list.</div>}{!loading&&!error&&visible.length===0&&<div className="note">{jobs.length?"No live jobs match your search.":"No live jobs have been posted yet."}</div>}{!loading&&!error&&visible.map(j=><button className="job" key={j.id} onClick={()=>setSelected(j)}><b>{j.title}</b><small>{j.category||"General work"} · {j.area||j.location_text||j.county}</small><footer><strong>{budget(j)}</strong><span>{when(j.created_at)}</span></footer></button>)}</div>{selected&&createPortal(<div className="backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section className="modal"><button className="close" onClick={()=>setSelected(null)}>×</button><em>LIVE JOB · OPEN</em><h2>{selected.title}</h2><small>📍 {selected.area||selected.location_text||selected.county}{selected.road?` · ${selected.road}`:""}</small><h3>{budget(selected)}</h3><p>{selected.description}</p><button className="action" onClick={async()=>{const {data}=await supabase.auth.getUser();const next=`/jobs/respond?job=${selected.id}`;window.location.href=data.user?next:`/login?next=${encodeURIComponent(next)}`}}>I’m interested in this job</button></section></div>,document.body)}<style jsx global>{`#kzk-live-jobs-mount{width:100%}.kzk-live-wrap{display:grid;gap:10px;margin-bottom:12px}.kzk-live-label{font-size:11px;font-weight:900;color:#13753a;text-transform:uppercase}.kzk-live-label span{display:inline-block;width:8px;height:8px;border-radius:50%;background:#16a34a;margin-right:6px}.note,.job{border:1px solid #dce5dd;border-radius:13px;background:#fff;padding:12px}.note{font-size:12px;color:#66736b}.job{text-align:left;cursor:pointer;display:grid;gap:5px;font-family:inherit;color:#17221b}.job small{color:#6a776f}.job footer{display:flex;justify-content:space-between;font-size:11px;margin-top:4px}.job footer strong{color:#176b35}.job footer span{color:#7d8781}.backdrop{position:fixed;inset:0;z-index:100000;background:rgba(15,23,18,.55);display:grid;place-items:center;padding:20px}.modal{position:relative;width:min(560px,96vw);background:white;border-radius:20px;padding:26px;font-family:Inter,system-ui;color:#17221b}.close{position:absolute;right:15px;top:10px;border:0;background:none;font-size:30px;cursor:pointer}.modal em{font-style:normal;font-size:10px;font-weight:900;color:#16803d}.modal h2{margin:8px 35px 6px 0}.modal h3{color:#156f37}.modal p{line-height:1.6;color:#48554c}.action{width:100%;border:0;border-radius:11px;background:#16803d;color:white;padding:13px;font-weight:850;cursor:pointer;margin-top:12px}`}</style></>,mount)
}
