"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import { supabase } from "../lib/supabase";

type DemoWorker={id:string;full_name:string;latitude:number|null;longitude:number|null;area:string|null;country_name:string;country_code:string};
type DemoJob={id:string;title:string;latitude:number|null;longitude:number|null;area:string|null;country_name:string;country_code:string};
type PointItem={id:string;latitude:number|null;longitude:number|null};

const STORAGE_KEY="anydaywork-marketplace-country";
function normalizeCountryCode(value:unknown){const code=String(value||"").trim().toUpperCase();return /^[A-Z]{2}$/.test(code)?code:""}
function workerMode(){const active=Array.from(document.querySelectorAll<HTMLElement>(".main-tab")).find(tab=>tab.classList.contains("active"));return !((active?.textContent||"").toLowerCase().includes("job"))}
function getMap(){const mapEl=document.querySelector<HTMLElement>(".leaflet-container") as any;if(!mapEl)return{mapEl:null,map:null};const w=window as any;const map=w.__kzkMarketplaceMap||mapEl.__kzkMarketplaceMap||mapEl._leaflet_map||Object.values(w).find((value:any)=>value&&typeof value==="object"&&value._container===mapEl&&typeof value.flyTo==="function"&&typeof value.addLayer==="function");return{mapEl,map}}
function validPoint(item:PointItem){if(item.latitude==null||item.longitude==null)return null;const lat=Number(item.latitude),lng=Number(item.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;return{lat,lng}}
function flyToItem(item:PointItem,zoom=15){const point=validPoint(item);if(!point)return;const{map}=getMap();if(!map)return;try{map.flyTo([point.lat,point.lng],zoom,{animate:true,duration:1.25})}catch{}}
function openDemoCard(kind:"worker"|"job",id:string){const selector=kind==="worker"?`.anyday-demo-worker-card[data-demo-id="${id}"]`:`.anyday-demo-job-card[data-demo-id="${id}"]`;const card=document.querySelector<HTMLElement>(selector);try{card?.click()}catch{}}

export default function MarketplaceDemoMapBridge(){
 const pathname=usePathname();const[workers,setWorkers]=useState<DemoWorker[]>([]);const[jobs,setJobs]=useState<DemoJob[]>([]);const[selectedCountry,setSelectedCountry]=useState("");

 useEffect(()=>{if(pathname!=="/")return;const fromUrl=normalizeCountryCode(new URLSearchParams(window.location.search).get("country"));let initial=fromUrl;try{if(!initial)initial=normalizeCountryCode(window.localStorage.getItem(STORAGE_KEY))}catch{}setSelectedCountry(initial||"KE");const onCountry=(event:Event)=>{const code=normalizeCountryCode((event as CustomEvent<{countryCode?:string}>).detail?.countryCode);if(code)setSelectedCountry(code)};window.addEventListener("anydaywork:country-changed",onCountry as EventListener);return()=>window.removeEventListener("anydaywork:country-changed",onCountry as EventListener)},[pathname]);

 useEffect(()=>{if(pathname!=="/"||!selectedCountry)return;let active=true;async function load(){const[{data:w,error:we},{data:j,error:je}]=await Promise.all([supabase.from("demo_profiles").select("id,full_name,latitude,longitude,area,country_name,country_code").eq("is_demo",true).eq("profile_kind","worker").eq("country_code",selectedCountry).order("sort_order"),supabase.from("demo_jobs").select("id,title,latitude,longitude,area,country_name,country_code").eq("is_demo",true).eq("country_code",selectedCountry).order("created_at")]);if(!active)return;if(we)console.error("Demo worker map profiles failed to load",we);else setWorkers((w||[]) as DemoWorker[]);if(je)console.error("Demo job map locations failed to load",je);else setJobs((j||[]) as DemoJob[])}void load();const timer=window.setInterval(load,30000);return()=>{active=false;window.clearInterval(timer)}},[pathname,selectedCountry]);
 const workersById=useMemo(()=>new Map(workers.map(w=>[w.id,w])),[workers]);const jobsById=useMemo(()=>new Map(jobs.map(j=>[j.id,j])),[jobs]);

 useEffect(()=>{if(pathname!=="/"||!selectedCountry)return;const countryPoints=[...workers,...jobs].map(validPoint).filter(Boolean) as {lat:number;lng:number}[];let attempts=0;const center=()=>{attempts+=1;const{mapEl,map}=getMap();const L=(window as any).L;if(!mapEl||!map)return false;try{if(countryPoints.length===1){map.setView([countryPoints[0].lat,countryPoints[0].lng],12,{animate:false})}else if(countryPoints.length>1&&L?.latLngBounds){const bounds=L.latLngBounds(countryPoints.map(point=>[point.lat,point.lng]));map.fitBounds(bounds,{padding:[55,55],maxZoom:12,animate:false})}else if(countryPoints.length>0){map.setView([countryPoints[0].lat,countryPoints[0].lng],11,{animate:false})}mapEl.classList.add("anyday-map-country-ready");window.setTimeout(()=>{try{map.invalidateSize?.()}catch{}},0);return true}catch{return false}};if(center())return;const timer=window.setInterval(()=>{if(center()||attempts>80){window.clearInterval(timer);const{mapEl}=getMap();mapEl?.classList.add("anyday-map-country-ready")}},100);return()=>window.clearInterval(timer)},[pathname,selectedCountry,workers,jobs]);

 useEffect(()=>{if(pathname!=="/")return;const fallback=window.setTimeout(()=>{const{mapEl}=getMap();mapEl?.classList.add("anyday-map-country-ready")},2500);return()=>window.clearTimeout(fallback)},[pathname]);

 useEffect(()=>{if(pathname!=="/"||(!workers.length&&!jobs.length))return;let cancelled=false;let mountedMap:any=null;let mountedMapEl:any=null;let workerGroup:any=null;let jobGroup:any=null;
  const mountMarkers=()=>{if(cancelled)return false;const{mapEl,map}=getMap();const L=(window as any).L;if(!mapEl||!map||!L)return false;mountedMap=map;mountedMapEl=mapEl;try{mapEl.__anydayDemoWorkerGroup?.remove?.();mapEl.__anydayDemoJobGroup?.remove?.()}catch{}
   workerGroup=L.layerGroup();jobGroup=L.layerGroup();
   workers.forEach(worker=>{const point=validPoint(worker);if(!point)return;const icon=L.divIcon({className:"anyday-demo-map-marker",html:'<div class="anyday-demo-map-pin anyday-demo-map-pin-worker">E</div>',iconSize:[38,38],iconAnchor:[19,19]});const marker=L.marker([point.lat,point.lng],{icon});marker.bindTooltip(`${worker.full_name} · EXAMPLE WORKER · ${worker.area||worker.country_name}`);marker.on("click",()=>{flyToItem(worker,16);window.setTimeout(()=>openDemoCard("worker",worker.id),250)});marker.addTo(workerGroup)});
   jobs.forEach(job=>{const point=validPoint(job);if(!point)return;const icon=L.divIcon({className:"anyday-demo-map-marker",html:'<div class="anyday-demo-map-pin anyday-demo-map-pin-job">J</div>',iconSize:[38,38],iconAnchor:[19,19]});const marker=L.marker([point.lat,point.lng],{icon});marker.bindTooltip(`${job.title} · EXAMPLE JOB · ${job.area||job.country_name}`);marker.on("click",()=>{flyToItem(job,16);window.setTimeout(()=>openDemoCard("job",job.id),250)});marker.addTo(jobGroup)});
   if(workerMode())workerGroup.addTo(map);else jobGroup.addTo(map);mapEl.__anydayDemoWorkerGroup=workerGroup;mapEl.__anydayDemoJobGroup=jobGroup;try{window.dispatchEvent(new CustomEvent("kzk:marketplace-layer-updated"))}catch{}return true};
  let attempts=0;const timer=window.setInterval(()=>{attempts+=1;if(mountMarkers()||attempts>80)window.clearInterval(timer)},250);mountMarkers();
  const syncMode=()=>{if(!mountedMap||!workerGroup||!jobGroup)return;try{if(workerMode()){if(!mountedMap.hasLayer?.(workerGroup))workerGroup.addTo(mountedMap);if(mountedMap.hasLayer?.(jobGroup))jobGroup.remove?.()}else{if(!mountedMap.hasLayer?.(jobGroup))jobGroup.addTo(mountedMap);if(mountedMap.hasLayer?.(workerGroup))workerGroup.remove?.()}}catch{}};
  const onClick=()=>window.setTimeout(syncMode,0);document.addEventListener("click",onClick,true);return()=>{cancelled=true;window.clearInterval(timer);document.removeEventListener("click",onClick,true);try{workerGroup?.remove?.();jobGroup?.remove?.()}catch{}if(mountedMapEl?.__anydayDemoWorkerGroup===workerGroup)mountedMapEl.__anydayDemoWorkerGroup=null;if(mountedMapEl?.__anydayDemoJobGroup===jobGroup)mountedMapEl.__anydayDemoJobGroup=null}},[pathname,workers,jobs]);

 useEffect(()=>{if(pathname!=="/")return;const zoomFromCard=(event:Event)=>{const target=event.target as HTMLElement|null;const workerCard=target?.closest?.(".anyday-demo-worker-card") as HTMLElement|null;if(workerCard){const worker=workersById.get(workerCard.dataset.demoId||"");if(worker)flyToItem(worker,15);return}const jobCard=target?.closest?.(".anyday-demo-job-card") as HTMLElement|null;if(jobCard){const job=jobsById.get(jobCard.dataset.demoId||"");if(job)flyToItem(job,15)}};document.addEventListener("click",zoomFromCard,true);return()=>document.removeEventListener("click",zoomFromCard,true)},[pathname,workersById,jobsById]);
 if(pathname!=="/")return null;
 return <style jsx global>{`.leaflet-container{visibility:hidden}.leaflet-container.anyday-map-country-ready{visibility:visible}.anyday-demo-map-marker{background:transparent!important;border:0!important}.anyday-demo-map-pin{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;color:#fff;border:3px solid #fff;box-shadow:0 3px 12px rgba(0,0,0,.32);font:900 12px/1 system-ui,sans-serif}.anyday-demo-map-pin-worker{background:#16803d}.anyday-demo-map-pin-job{background:#7c3aed}`}</style>
}
