"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { usePathname, useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";

type DemoProfile={id:string;full_name:string;profile_kind:"worker"|"employer";country_code:string;country_name:string;area:string|null;avatar_url:string|null;bio:string|null;years_experience:number|null;occupation:string|null;example_label:string;latitude:number|null;longitude:number|null};
type DemoJob={id:string;employer_profile_id:string;title:string;description:string;category:string|null;budget_min:number|null;budget_max:number|null;country_name:string;area:string|null;latitude:number|null;longitude:number|null;example_label:string;created_at:string};

function money(v:number|null){return v==null?null:`KSh ${Number(v).toLocaleString("en-KE")}`}
function budget(j:DemoJob){const a=money(j.budget_min),b=money(j.budget_max);return a&&b?`${a} - ${b}`:a?`From ${a}`:b?`Up to ${b}`:"Budget to discuss"}
function activeMode(){const active=Array.from(document.querySelectorAll<HTMLElement>(".main-tab")).find(t=>t.classList.contains("active"));return((active?.textContent||"").toLowerCase().includes("job"))?"jobs":"workers"}

export default function MarketplaceDemoContent(){
 const pathname=usePathname();const router=useRouter();
 const[workersMount,setWorkersMount]=useState<HTMLElement|null>(null);const[jobsMount,setJobsMount]=useState<HTMLElement|null>(null);
 const[profiles,setProfiles]=useState<DemoProfile[]>([]);const[jobs,setJobs]=useState<DemoJob[]>([]);const[search,setSearch]=useState("");const[selected,setSelected]=useState<DemoJob|null>(null);

 useEffect(()=>{if(pathname!=="/")return;let stopped=false;const attach=()=>{const workerTitle=Array.from(document.querySelectorAll<HTMLElement>(".section-title")).find(n=>(n.textContent||"").replace(/\s+/g," ").trim().toLowerCase().startsWith("people who can help"));const jobTitle=Array.from(document.querySelectorAll<HTMLElement>(".section-title")).find(n=>(n.textContent||"").replace(/\s+/g," ").trim()==="Jobs people need done");if(workerTitle?.parentElement){let m=document.getElementById("anyday-demo-workers-mount") as HTMLElement|null;if(!m){m=document.createElement("div");m.id="anyday-demo-workers-mount";const live=document.getElementById("kzk-live-workers-mount");(live||workerTitle).insertAdjacentElement("afterend",m)}if(!stopped)setWorkersMount(m)}if(jobTitle?.parentElement){let m=document.getElementById("anyday-demo-jobs-mount") as HTMLElement|null;if(!m){m=document.createElement("div");m.id="anyday-demo-jobs-mount";const live=document.getElementById("kzk-live-jobs-mount");(live||jobTitle).insertAdjacentElement("afterend",m)}if(!stopped)setJobsMount(m)}};attach();const observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});const capture=(e:Event)=>{const i=e.target as HTMLInputElement|null;if(!i||i.tagName!=="INPUT")return;const p=(i.placeholder||"").toLowerCase();if(p.includes("search")||p.includes("service")||p.includes("what do you need"))setSearch(i.value||"")};document.addEventListener("input",capture,true);return()=>{stopped=true;observer.disconnect();document.removeEventListener("input",capture,true)}},[pathname]);

 useEffect(()=>{if(pathname!=="/")return;let active=true;(async()=>{const[{data:p},{data:j}]=await Promise.all([supabase.from("demo_profiles").select("id,full_name,profile_kind,country_code,country_name,area,avatar_url,bio,years_experience,occupation,example_label,latitude,longitude").eq("is_demo",true),supabase.from("demo_jobs").select("id,employer_profile_id,title,description,category,budget_min,budget_max,country_name,area,latitude,longitude,example_label,created_at").eq("is_demo",true)]);if(!active)return;setProfiles((p||[]) as DemoProfile[]);setJobs((j||[]) as DemoJob[])})();return()=>{active=false}},[pathname]);

 const demoWorkers=useMemo(()=>{const q=search.trim().toLowerCase();const list=profiles.filter(p=>p.profile_kind==="worker");if(!q)return list;return list.filter(p=>[p.full_name,p.occupation,p.bio,p.area,p.country_name].filter(Boolean).join(" ").toLowerCase().includes(q))},[profiles,search]);
 const demoJobs=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return jobs;return jobs.filter(j=>[j.title,j.description,j.category,j.area,j.country_name].filter(Boolean).join(" ").toLowerCase().includes(q))},[jobs,search]);
 const employers=useMemo(()=>new Map(profiles.filter(p=>p.profile_kind==="employer").map(p=>[p.id,p])),[profiles]);

 useEffect(()=>{if(pathname!=="/")return;let cancelled=false;const sync=()=>{if(cancelled)return;const mapEl=document.querySelector<HTMLElement>(".leaflet-container") as any;const map=(window as any).__kzkMarketplaceMap||mapEl?._leaflet_map;const L=(window as any).L;if(!mapEl||!map||!L)return;
  const rebuild=(group:any,kind:"worker"|"job")=>{if(!group)return;const source=(group.__kzkSourceMarkers||group.getLayers?.()||[]).filter((m:any)=>!m.__anydayDemo);(group.getLayers?.()||[]).filter((m:any)=>m.__anydayDemo).forEach((m:any)=>{try{group.removeLayer(m)}catch{}});group.__kzkSourceMarkers=source;const rows=kind==="worker"?demoWorkers:demoJobs;rows.forEach((row:any)=>{if(row.latitude==null||row.longitude==null)return;const html=kind==="worker"?'<div style="width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#16803d;border:3px solid white;box-shadow:0 2px 9px rgba(0,0,0,.28);color:white;font:900 11px system-ui">E</div>':'<div style="width:30px;height:30px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#b91c1c;border:3px solid white;box-shadow:0 2px 8px rgba(0,0,0,.25)"><div style="transform:rotate(45deg);text-align:center;line-height:24px;color:white;font:900 10px system-ui">E</div></div>';const icon=L.divIcon({className:"anyday-demo-marker",html,iconSize:kind==="worker"?[34,34]:[30,30],iconAnchor:kind==="worker"?[17,17]:[15,30]});const marker=L.marker([Number(row.latitude),Number(row.longitude)],{icon});marker.__anydayDemo=true;marker.bindTooltip(kind==="worker"?`${row.full_name} · EXAMPLE`:`${row.title} · EXAMPLE`);marker.on("click",()=>kind==="worker"?router.push(`/profile/demo/${row.id}`):setSelected(row as DemoJob));group.__kzkSourceMarkers.push(marker);try{group.addLayer(marker)}catch{}});};
  rebuild(mapEl.__kzkLiveWorkerGroup,"worker");rebuild(mapEl.__kzkLiveGroup,"job");try{window.dispatchEvent(new CustomEvent("kzk:marketplace-layer-updated"))}catch{}
 };
 const timer=window.setInterval(sync,1000);const onUpdate=()=>window.setTimeout(sync,80);window.addEventListener("kzk:leaflet-map-ready",onUpdate);return()=>{cancelled=true;window.clearInterval(timer);window.removeEventListener("kzk:leaflet-map-ready",onUpdate)}},[pathname,demoWorkers,demoJobs,router]);

 useEffect(()=>{if(pathname!=="/")return;const sync=()=>{const mode=activeMode();if(workersMount)workersMount.style.display=mode==="workers"?"":"none";if(jobsMount)jobsMount.style.display=mode==="jobs"?"":"none"};sync();document.addEventListener("click",sync,true);return()=>document.removeEventListener("click",sync,true)},[pathname,workersMount,jobsMount]);

 if(pathname!=="/")return null;
 const workerPortal=workersMount?createPortal(<div className="anyday-demo-list">{demoWorkers.map(p=><button key={p.id} className="live-worker-card anyday-demo-card" type="button" onClick={()=>router.push(`/profile/demo/${p.id}`)}><div className="worker-top">{p.avatar_url?<img src={p.avatar_url} alt="Example profile"/>:<div className="worker-avatar">👤</div>}<div className="worker-main"><div className="worker-name-row"><b>{p.full_name}</b><span className="anyday-example-badge">EXAMPLE</span></div><p>{p.occupation||"Worker / service provider"}</p><small>📍 {[p.area,p.country_name].filter(Boolean).join(", ")}</small><div className="worker-inline-stats"><span>{p.years_experience!=null?`${p.years_experience} years experience`:"Example profile"}</span><strong>Demo only</strong></div></div></div><div className="worker-proof">EXAMPLE — NOT A REAL USER · View profile</div></button>)}</div>,workersMount):null;
 const jobsPortal=jobsMount?createPortal(<div className="anyday-demo-list">{demoJobs.map(j=><button className="job anyday-demo-card" key={j.id} onClick={()=>setSelected(j)}><div className="anyday-job-title"><b>{j.title}</b><span className="anyday-example-badge">EXAMPLE</span></div><small>{j.category||"General work"} · {j.area||j.country_name}</small><footer><strong>{budget(j)}</strong><span>Not a real vacancy</span></footer></button>)}</div>,jobsMount):null;
 return <>{workerPortal}{jobsPortal}{selected&&createPortal(<div className="anyday-demo-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section className="anyday-demo-modal"><button className="close" onClick={()=>setSelected(null)}>×</button><em>EXAMPLE JOB — NOT A REAL VACANCY</em><h2>{selected.title}</h2><small>📍 {selected.area||selected.country_name}</small><h3>{budget(selected)}</h3><p>{selected.description}</p>{employers.get(selected.employer_profile_id)&&<button className="viewEmployer" onClick={()=>router.push(`/profile/demo/${selected.employer_profile_id}`)}>View example employer profile →</button>}<p className="demoNote">This demonstration cannot be applied to, accepted, messaged or rated.</p></section></div>,document.body)}<style jsx global>{`.anyday-demo-list{display:grid;gap:10px;margin-bottom:10px}.anyday-demo-card{position:relative}.anyday-example-badge{display:inline-block!important;background:#fff4cc!important;color:#775700!important;border:1px solid #e7ca64!important;border-radius:999px!important;padding:4px 7px!important;font-size:8px!important;font-weight:900!important;white-space:nowrap}.anyday-job-title{display:flex;justify-content:space-between;gap:8px;align-items:center}.anyday-demo-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.44);z-index:99999;display:grid;place-items:center;padding:18px}.anyday-demo-modal{position:relative;width:min(560px,100%);max-height:86vh;overflow:auto;background:#fff;border-radius:18px;padding:24px;color:#17221b;box-shadow:0 20px 70px rgba(0,0,0,.28);font-family:Inter,system-ui,sans-serif}.anyday-demo-modal .close{position:absolute;right:14px;top:10px;border:0;background:transparent;font-size:28px;cursor:pointer}.anyday-demo-modal em{display:inline-block;background:#fff4cc;color:#775700;border-radius:999px;padding:6px 9px;font-style:normal;font-size:10px;font-weight:900}.anyday-demo-modal h2{margin:16px 0 5px}.anyday-demo-modal h3{color:#15803d}.anyday-demo-modal p{line-height:1.55}.viewEmployer{border:0;background:#15803d;color:white;border-radius:10px;padding:11px 14px;font-weight:850;cursor:pointer}.demoNote{font-size:11px;color:#7a6a35;border-top:1px solid #eee5c7;padding-top:12px;margin-top:16px}.anyday-demo-marker{background:transparent!important;border:0!important}`}</style></>;
}
