"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { usePathname } from "next/navigation";
import { supabase } from "../lib/supabase";

type DemoProfile={id:string;full_name:string;country_code:string;country_name:string;area:string|null;avatar_url:string|null;occupation:string|null;years_experience:number|null;profile_kind:"worker"|"employer"};
const STORAGE_KEY="anydaywork-marketplace-country";
function selectedCountry(){const q=new URLSearchParams(window.location.search).get("country");if(q&&/^[A-Za-z]{2}$/.test(q))return q.toUpperCase();try{return(window.localStorage.getItem(STORAGE_KEY)||"KE").toUpperCase()}catch{return"KE"}}
function selectedCountryName(code:string){try{return new Intl.DisplayNames(["en"],{type:"region"}).of(code)||code}catch{return code}}
function workerAnchor(){const live=document.getElementById("kzk-live-workers-mount");if(live?.parentElement)return{anchor:live,parent:live.parentElement,mode:"before" as const};const title=Array.from(document.querySelectorAll<HTMLElement>(".section-title")).find(n=>(n.textContent||"").toLowerCase().includes("people who can help"));if(title?.parentElement)return{anchor:title,parent:title.parentElement,mode:"after" as const};const card=document.querySelector<HTMLElement>(".provider,.worker");if(card?.parentElement)return{anchor:card,parent:card.parentElement,mode:"before" as const};return null}
export default function MarketplaceCountryDemoProfiles(){const pathname=usePathname();const[countryCode,setCountryCode]=useState("KE");const[profiles,setProfiles]=useState<DemoProfile[]>([]);const[mount,setMount]=useState<HTMLElement|null>(null);
 useEffect(()=>{if(pathname!=="/")return;setCountryCode(selectedCountry());const fn=(e:Event)=>{const c=String((e as CustomEvent<{countryCode?:string}>).detail?.countryCode||"").toUpperCase();if(/^[A-Z]{2}$/.test(c))setCountryCode(c)};window.addEventListener("anydaywork:country-changed",fn as EventListener);return()=>window.removeEventListener("anydaywork:country-changed",fn as EventListener)},[pathname]);
 useEffect(()=>{if(pathname!=="/")return;let off=false,timer=0,tries=0;const attach=()=>{if(off)return;let host=document.getElementById("anyday-country-demo-profiles-mount")as HTMLElement|null;if(host&&document.body.contains(host)){setMount(host);return}const found=workerAnchor();if(found){host=document.createElement("div");host.id="anyday-country-demo-profiles-mount";if(found.mode==="after")found.anchor.insertAdjacentElement("afterend",host);else found.parent.insertBefore(host,found.anchor);setMount(host);return}if(++tries<120)timer=window.setTimeout(attach,100)};const retry=()=>{tries=0;window.clearTimeout(timer);window.setTimeout(attach,30)};const tab=(e:MouseEvent)=>{if((e.target as Element|null)?.closest(".main-tab"))retry()};attach();document.addEventListener("click",tab,true);window.addEventListener("anydaywork:country-changed",retry);return()=>{off=true;window.clearTimeout(timer);document.removeEventListener("click",tab,true);window.removeEventListener("anydaywork:country-changed",retry)}},[pathname]);
 useEffect(()=>{if(pathname!=="/"||!countryCode)return;let active=true;setProfiles([]);async function load(){const{data,error}=await supabase.from("demo_profiles").select("id,full_name,country_code,country_name,area,avatar_url,occupation,years_experience,profile_kind").eq("is_demo",true).eq("profile_kind","worker").order("sort_order");if(!active)return;if(error){setProfiles([]);return}const code=countryCode.toUpperCase(),name=selectedCountryName(code).trim().toLowerCase(),aliases=code==="CZ"?["czechia","czech republic"]:[name];setProfiles(((data||[])as DemoProfile[]).filter(p=>String(p.country_code||"").trim().toUpperCase()===code||aliases.includes(String(p.country_name||"").trim().toLowerCase())))}void load();return()=>{active=false}},[pathname,countryCode]);
 useEffect(()=>{if(pathname!=="/")return;let timer=0;const apply=()=>{const core=Array.from(document.querySelectorAll<HTMLElement>(".worker,.provider"));const live=document.getElementById("kzk-live-workers-mount")as HTMLElement|null;const demo=document.getElementById("anyday-country-demo-profiles-mount")as HTMLElement|null;if(countryCode!=="KE"){core.forEach(c=>c.style.setProperty("display","none","important"));if(live)live.style.setProperty("display","none","important");if(demo)demo.style.setProperty("display","block","important")}else{core.forEach(c=>c.style.removeProperty("display"));if(live)live.style.removeProperty("display");if(demo)demo.style.removeProperty("display")}};apply();timer=window.setInterval(apply,1000);return()=>window.clearInterval(timer)},[pathname,countryCode]);
 if(pathname!=="/"||!mount||countryCode==="KE")return null;return createPortal(<div className="anyday-country-demo-profiles">{profiles.length===0?<div className="anyday-country-demo-note">No example worker profiles are available for {selectedCountryName(countryCode)} yet.</div>:profiles.map(p=><button key={p.id} className="anyday-country-demo-card" type="button" onClick={()=>window.location.href=`/profile/demo/${p.id}`}>{p.avatar_url?<img src={p.avatar_url} alt="Example worker profile"/>:<div className="avatar">👤</div>}<div className="main"><div className="name"><b>{p.full_name}</b><span>EXAMPLE</span></div><p>{p.occupation||"Service provider"}</p><small>📍 {[p.area,p.country_name].filter(Boolean).join(", ")}</small><footer>{p.years_experience!=null?`${p.years_experience} years experience`:"Example profile"}</footer></div></button>)}<style jsx global>{`#anyday-country-demo-profiles-mount{display:block!important;width:100%!important;min-height:1px!important}.anyday-country-demo-profiles{display:grid!important;gap:10px!important;margin:0 0 10px!important;width:100%!important}.anyday-country-demo-note{padding:12px;border:1px solid #dce4dc;border-radius:12px;background:#fff;color:#657168;font-size:12px}.anyday-country-demo-card{display:flex!important;align-items:center;gap:12px;width:100%;padding:11px;border:1px solid #dce4dc;border-radius:14px;background:#fff;text-align:left;font-family:inherit;cursor:pointer}.anyday-country-demo-card img,.anyday-country-demo-card .avatar{width:64px;height:64px;border-radius:50%;object-fit:cover;flex:0 0 64px;background:#eef5ef}.anyday-country-demo-card .avatar{display:grid;place-items:center;font-size:28px}.anyday-country-demo-card .main{min-width:0;flex:1}.anyday-country-demo-card .name{display:flex;justify-content:space-between;gap:8px}.anyday-country-demo-card .name span{font-size:9px;font-weight:900;color:#8a5b00;background:#fff3cd;border-radius:999px;padding:3px 6px}.anyday-country-demo-card p{margin:4px 0;color:#52645a;font-size:11px;font-weight:650}.anyday-country-demo-card small,.anyday-country-demo-card footer{display:block;color:#77847c;font-size:9px}.anyday-country-demo-card footer{margin-top:6px;color:#176f3a;font-weight:700}`}</style></div>,mount)}