"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "../../../../lib/supabase";

type DemoProfile={id:string;full_name:string;profile_kind:"worker"|"employer";country_name:string;area:string|null;avatar_url:string|null;bio:string|null;years_experience:number|null;occupation:string|null;example_label:string};

export default function DemoProfilePage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const[profile,setProfile]=useState<DemoProfile|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{setLoading(true);const{data,error:e}=await supabase.from("demo_profiles").select("id,full_name,profile_kind,country_name,area,avatar_url,bio,years_experience,occupation,example_label").eq("id",id).eq("is_demo",true).maybeSingle();if(!active)return;if(e||!data){setError(e?.message||"Example profile not found.");setProfile(null)}else setProfile(data as DemoProfile);setLoading(false)})();return()=>{active=false}},[id]);
 if(loading)return <main className="page"><section className="card">Loading example profile…</section><style jsx>{styles}</style></main>;
 return <main className="page"><section className="card"><button className="back" onClick={()=>router.back()}>← Back</button>{error&&!profile?<div className="error">{error}</div>:profile&&<><div className="notice"><b>EXAMPLE — NOT A REAL USER</b><span>This profile is here only to show how AnyDayWork works.</span></div><header>{profile.avatar_url?<img src={profile.avatar_url} alt="Example profile"/>:<div className="blank">👤</div>}<div><h1>{profile.full_name}</h1><p>{[profile.area,profile.country_name].filter(Boolean).join(", ")} · {profile.profile_kind==="worker"?"Worker / service provider":"Employer"}</p><small>{profile.occupation||"Example profile"}</small></div></header>{profile.bio&&<p className="bio">{profile.bio}</p>}{profile.years_experience!=null&&<p className="experience"><b>Experience:</b> {profile.years_experience} year{profile.years_experience===1?"":"s"}</p>}<section className="feedback"><div className="feedbackHead"><div><h2>Work feedback</h2><p>Real AnyDayWork profiles can earn feedback after completed work.</p></div></div><div className="empty">No real reviews are attached to example profiles.</div></section><div className="disabledActions"><button disabled>Message unavailable</button><button disabled>Hire / apply unavailable</button></div><p className="foot">Example profiles cannot message, hire, apply, rate or receive reviews. They can all be removed together later without touching real users.</p></>}</section><style jsx>{styles}</style></main>}
const styles=`*{box-sizing:border-box}.page{min-height:100vh;background:#f3f6f3;padding:30px 16px;font-family:Inter,system-ui,sans-serif;color:#17221b}.card{max-width:780px;margin:auto;background:#fff;border:1px solid #dce4dc;border-radius:20px;padding:28px;box-shadow:0 12px 40px rgba(27,43,31,.1)}.back{border:0;background:transparent;color:#15803d;font-weight:800;cursor:pointer;padding:0;margin-bottom:22px}.notice{display:flex;justify-content:space-between;gap:12px;align-items:center;background:#fff8dc;border:1px solid #ebd47b;border-radius:11px;padding:11px 13px;margin-bottom:18px;color:#715500;font-size:12px}.notice b{font-size:10px;letter-spacing:.04em}.notice span{color:#756b45}header{display:flex;gap:16px;align-items:center;padding-bottom:20px;border-bottom:1px solid #e5ebe6}header img,.blank{width:78px;height:78px;border-radius:50%;object-fit:cover;border:2px solid #dce8df}.blank{display:grid;place-items:center;background:#eef5ef;font-size:32px}h1{margin:0 0 5px;font-size:28px}header p{margin:0;color:#68756d}header small{display:inline-block;margin-top:7px;text-transform:capitalize;color:#176b35;background:#edf8f0;padding:4px 7px;border-radius:999px}.bio{line-height:1.6;color:#526057}.experience{font-size:13px}.feedback{margin-top:28px}.feedbackHead h2{margin:0 0 5px;font-size:20px}.feedbackHead p{margin:0;color:#758078;font-size:12px;line-height:1.45}.empty{margin-top:13px;background:#f7faf7;color:#748078;padding:15px;border-radius:11px}.disabledActions{display:flex;gap:10px;margin-top:20px}.disabledActions button{border:1px solid #d8dfd9;background:#f3f5f3;color:#8a938d;border-radius:10px;padding:10px 13px;font-weight:800}.foot{font-size:11px;color:#7f7655;border-top:1px solid #eee8d1;margin-top:20px;padding-top:14px}.error{background:#fff1f1;border:1px solid #efcaca;color:#9b2929;border-radius:10px;padding:11px 13px;margin:10px 0}@media(max-width:600px){.card{padding:20px}.notice{display:block}.notice span{display:block;margin-top:5px}h1{font-size:23px}.disabledActions{flex-direction:column}}`;
