"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "../../../lib/supabase";

type Profile={id:string;full_name:string|null;role:string|null;area:string|null;bio:string|null;years_experience:number|null;profile_photo_url:string|null;avatar_url:string|null;verification_status:string|null;country_code:string|null};
type Review={id:string;rating:number;comment:string|null;created_at:string;reviewer_id:string;job_id:string;reviewer?:{full_name:string|null}|null;job?:{title:string}|null};
type PortfolioItem={id:string;title:string;description:string|null;photo_url:string|null;moderation_status:string|null;created_at:string};

function countryName(code:string|null|undefined){if(!code)return"";try{return new Intl.DisplayNames(["en"],{type:"region"}).of(code.toUpperCase())||code.toUpperCase()}catch{return code.toUpperCase()}}

export default function PublicProfilePage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [profile,setProfile]=useState<Profile|null>(null); const [reviews,setReviews]=useState<Review[]>([]); const [portfolio,setPortfolio]=useState<PortfolioItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [uid,setUid]=useState(""); const [reported,setReported]=useState<Set<string>>(new Set()); const [reporting,setReporting]=useState("");
 useEffect(()=>{void load()},[id]);
 async function load(){
  setLoading(true);setError("");
  const {data:{user}}=await supabase.auth.getUser();setUid(user?.id||"");
  const [{data:p,error:pe},{data:r,error:re},{data:items,error:ie}]=await Promise.all([
   supabase.from("profiles").select("id,full_name,role,area,bio,years_experience,profile_photo_url,avatar_url,verification_status,country_code").eq("id",id).maybeSingle(),
   supabase.from("reviews").select("id,rating,comment,created_at,reviewer_id,job_id,reviewer:profiles!reviews_reviewer_id_fkey(full_name),job:jobs!reviews_job_id_fkey(title)").eq("reviewee_id",id).order("created_at",{ascending:false}),
   supabase.from("portfolio_items").select("id,title,description,photo_url,moderation_status,created_at").eq("provider_id",id).neq("moderation_status","rejected").order("created_at",{ascending:false})
  ]);
  if(pe||!p){setError(pe?.message||"Profile not found.");setLoading(false);return}
  if(re)setError(re.message);else if(ie)setError(ie.message);
  setProfile(p as Profile);setReviews((r||[]) as unknown as Review[]);setPortfolio((items||[]) as PortfolioItem[]);
  if(user){const {data:rr}=await supabase.from("review_reports").select("review_id").eq("reporter_id",user.id);setReported(new Set((rr||[]).map((x:any)=>x.review_id)))}
  setLoading(false)
 }
 async function reportReview(reviewId:string){if(!uid){router.push(`/login?next=${encodeURIComponent(`/profile/${id}`)}`);return}const reason=window.prompt("Why are you reporting this review? Enter: harassment, personal_information, discrimination, spam, false_or_unrelated, or other.","other");if(!reason)return;const allowed=["harassment","personal_information","discrimination","spam","false_or_unrelated","other"];if(!allowed.includes(reason)){setError("Please use one of the listed report reasons.");return}const details=window.prompt("Optional: briefly explain the problem (up to 500 characters).","")||"";setReporting(reviewId);setError("");const {error:e}=await supabase.from("review_reports").insert({review_id:reviewId,reporter_id:uid,reason,details:details.trim().slice(0,500)||null});setReporting("");if(e){if(e.code==="23505")setReported(s=>new Set([...s,reviewId]));else setError(e.message);return}setReported(s=>new Set([...s,reviewId]))}
 const avg=reviews.length?reviews.reduce((a,r)=>a+Number(r.rating),0)/reviews.length:0; const photo=profile?.profile_photo_url||profile?.avatar_url; const location=[profile?.area,countryName(profile?.country_code)].filter(Boolean).join(", ")||"Location not set";
 if(loading)return <main className="page"><section className="card">Loading profile…</section><style jsx>{styles}</style></main>;
 return <main className="page"><section className="card"><button className="back" onClick={()=>router.back()}>← Back</button>{error&&!profile?<div className="error">{error}</div>:profile&&<><header>{photo?<img src={photo} alt="Profile"/>:<div className="blank">👤</div>}<div><h1>{profile.full_name||"AnyDayWork member"}</h1><p>{location} · {profile.role||"member"}</p>{profile.verification_status&&<small>{profile.verification_status.replaceAll("_"," ")}</small>}</div></header>{profile.bio&&<p className="bio">{profile.bio}</p>}{profile.years_experience!=null&&<p className="experience"><b>Experience:</b> {profile.years_experience} year{profile.years_experience===1?"":"s"}</p>}
 {portfolio.length>0&&<section className="portfolio"><div className="sectionHead"><h2>Work photos</h2><span>{portfolio.length} photo{portfolio.length===1?"":"s"}</span></div><div className="gallery">{portfolio.map(item=>item.photo_url?<figure key={item.id}><img src={item.photo_url} alt={item.title||"Work photo"}/><figcaption><b>{item.title}</b>{item.description&&<span>{item.description}</span>}</figcaption></figure>:null)}</div></section>}
 <section className="feedback"><div className="feedbackHead"><div><h2>Verified Work Feedback</h2><p>Reviews can only come from people connected through completed AnyDayWork jobs.</p></div>{reviews.length>0&&<strong>⭐ {avg.toFixed(1)} · {reviews.length} review{reviews.length===1?"":"s"}</strong>}</div>{error&&<div className="error">{error}</div>}{reviews.length===0?<div className="empty">No verified work feedback yet.</div>:reviews.map(r=><article key={r.id}><div className="stars">{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</div>{r.comment?<p className="comment">“{r.comment}”</p>:<p className="noComment">Rating left without a written comment.</p>}<div className="meta"><b>{r.reviewer?.full_name||"Verified participant"}</b><span>✓ Verified completed job{r.job?.title?` · ${r.job.title}`:""}</span><time>{new Date(r.created_at).toLocaleDateString()}</time></div>{r.reviewer_id!==uid&&(reported.has(r.id)?<div className="reported">✓ Report submitted for review</div>:<button className="report" disabled={reporting===r.id} onClick={()=>reportReview(r.id)}>{reporting===r.id?"Reporting…":"Report review"}</button>)}</article>)}</section></>}</section><style jsx>{styles}</style></main>}

const styles=`*{box-sizing:border-box}.page{min-height:100vh;background:#f3f6f3;padding:30px 16px;font-family:Inter,system-ui,sans-serif;color:#17221b}.card{max-width:780px;margin:auto;background:#fff;border:1px solid #dce4dc;border-radius:20px;padding:28px;box-shadow:0 12px 40px rgba(27,43,31,.1)}.back{border:0;background:transparent;color:#15803d;font-weight:800;cursor:pointer;padding:0;margin-bottom:22px}header{display:flex;gap:16px;align-items:center;padding-bottom:20px;border-bottom:1px solid #e5ebe6}header img,.blank{width:78px;height:78px;border-radius:50%;object-fit:cover;border:2px solid #dce8df}.blank{display:grid;place-items:center;background:#eef5ef;font-size:32px}h1{margin:0 0 5px;font-size:28px}header p{margin:0;color:#68756d}header small{display:inline-block;margin-top:7px;text-transform:capitalize;color:#176b35;background:#edf8f0;padding:4px 7px;border-radius:999px}.bio{line-height:1.6;color:#526057}.experience{font-size:13px}.portfolio,.feedback{margin-top:28px}.sectionHead{display:flex;align-items:center;justify-content:space-between;gap:12px}.sectionHead h2{margin:0;font-size:20px}.sectionHead span{font-size:12px;color:#68756d}.gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.gallery figure{margin:0;border:1px solid #e0e7e1;border-radius:12px;overflow:hidden;background:#fafcfa}.gallery img{width:100%;aspect-ratio:4/3;display:block;object-fit:cover}.gallery figcaption{display:grid;gap:3px;padding:9px;font-size:11px}.gallery figcaption span{color:#758078}.feedbackHead{display:flex;justify-content:space-between;gap:18px;align-items:start}.feedbackHead h2{margin:0 0 5px;font-size:20px}.feedbackHead p{margin:0;color:#758078;font-size:12px;line-height:1.45}.feedbackHead strong{white-space:nowrap;color:#946700;font-size:13px}article{border:1px solid #e0e7e1;border-radius:13px;padding:15px;margin-top:11px}.stars{color:#a36e00;font-size:17px;letter-spacing:1px}.comment{line-height:1.55;margin:10px 0}.noComment{color:#7b867f;font-size:12px;font-style:italic}.meta{display:flex;gap:8px;align-items:center;flex-wrap:wrap;font-size:11px;color:#748078}.meta b{color:#425048}.meta span{color:#176b35;background:#eff8f1;padding:4px 7px;border-radius:999px}.meta time{margin-left:auto}.report{margin-top:11px;border:0;background:transparent;color:#8b5555;font-size:11px;font-weight:750;cursor:pointer;padding:0}.reported{margin-top:11px;color:#68756d;font-size:11px}.empty{margin-top:13px;background:#f7faf7;color:#748078;padding:15px;border-radius:11px}.error{background:#fff1f1;border:1px solid #efcaca;color:#9b2929;border-radius:10px;padding:11px 13px;margin:10px 0}@media(max-width:600px){.card{padding:20px}.feedbackHead{display:block}.feedbackHead strong{display:block;margin-top:9px}.meta time{width:100%;margin-left:0}h1{font-size:23px}.gallery{grid-template-columns:1fr 1fr}}`;